// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYd1alLSzOQZ_-2V66CSy-v12UDkSjiSo',
    appId: '1:450490963024:web:2429116afdb414e2b12d55',
    messagingSenderId: '450490963024',
    projectId: 'vista-project-6496a',
    authDomain: 'vista-project-6496a.firebaseapp.com',
    storageBucket: 'vista-project-6496a.firebasestorage.app',
    measurementId: 'G-3J5DHQBKRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsmWvBafsZLEVJss3Re-CPfFjyRKFs-eg',
    appId: '1:450490963024:android:fac8980d32f7b317b12d55',
    messagingSenderId: '450490963024',
    projectId: 'vista-project-6496a',
    storageBucket: 'vista-project-6496a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByVprQYHeBdp1NiHLrdHG8XgI35PypSkM',
    appId: '1:450490963024:ios:3fe8e65b155c2bcab12d55',
    messagingSenderId: '450490963024',
    projectId: 'vista-project-6496a',
    storageBucket: 'vista-project-6496a.firebasestorage.app',
    iosBundleId: 'com.example.vistaNotes2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByVprQYHeBdp1NiHLrdHG8XgI35PypSkM',
    appId: '1:450490963024:ios:3fe8e65b155c2bcab12d55',
    messagingSenderId: '450490963024',
    projectId: 'vista-project-6496a',
    storageBucket: 'vista-project-6496a.firebasestorage.app',
    iosBundleId: 'com.example.vistaNotes2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYd1alLSzOQZ_-2V66CSy-v12UDkSjiSo',
    appId: '1:450490963024:web:f8ecd810362353f0b12d55',
    messagingSenderId: '450490963024',
    projectId: 'vista-project-6496a',
    authDomain: 'vista-project-6496a.firebaseapp.com',
    storageBucket: 'vista-project-6496a.firebasestorage.app',
    measurementId: 'G-MFF0MH545E',
  );
}
